create table public.products (
    product_id bigint generated by default as identity primary key,
    product_code text not null unique,
    product_name text not null,
    product_image text,
    product_price numeric not null,
    product_category text,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    deleted_at timestamp without time zone
);


create table public.transactions (
    transaction_id bigint generated by default as identity primary key,
    transaction_code text not null unique,
    transaction_time timestamp without time zone not null default now(),
    payment_method text not null,
    transaction_amount numeric not null,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    deleted_at timestamp without time zone
);

create table public.transaction_items (
    transaction_item_id bigint generated by default as identity primary key,
    transaction_id bigint not null
        references public.transactions(transaction_id),
    product_id bigint not null
        references public.products(product_id),
    quantity integer not null,
    unit_price numeric not null,
    subtotal numeric not null,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    deleted_at timestamp without time zone,
    description text;
);



create index idx_transaction_items_transaction_id
on public.transaction_items(transaction_id);

create index idx_transaction_items_product_id
on public.transaction_items(product_id);


create or replace function public.update_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


create trigger products_updated_at
before update on public.products
for each row
execute function public.update_updated_at();


create trigger transactions_updated_at
before update on public.transactions
for each row
execute function public.update_updated_at();


create trigger transaction_items_updated_at
before update on public.transaction_items
for each row
execute function public.update_updated_at();