CREATE TABLE public.orders (
    order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_name text NOT NULL,
    customer_address text NULL,

    due_date date NOT NULL,

    status text NOT NULL DEFAULT 'pending',

    notes text NULL,

    transaction_id bigint NULL,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT orders_status_check
        CHECK (status IN ('pending', 'delivered', 'paid', 'cancelled')),

    CONSTRAINT orders_transaction_id_fkey
        FOREIGN KEY (transaction_id)
        REFERENCES public.transactions(transaction_id)
        ON DELETE SET NULL
);

CREATE TABLE public.order_items (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id bigint NOT NULL,

    product_id bigint NOT NULL,

    quantity_ordered integer NOT NULL,

    unit_price numeric NOT NULL,

    unit_cost_labor numeric NOT NULL DEFAULT 0,
    unit_cost_ingredient numeric NOT NULL DEFAULT 0,
    unit_cost_utilities numeric NOT NULL DEFAULT 0,
    unit_cost_packaging numeric NOT NULL DEFAULT 0,

    is_ready_override boolean NULL,

    CONSTRAINT order_items_order_id_fkey
        FOREIGN KEY (order_id)
        REFERENCES public.orders(order_id)
        ON DELETE CASCADE,

    CONSTRAINT order_items_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES public.products(product_id)
        ON DELETE RESTRICT,

    CONSTRAINT order_items_quantity_positive
        CHECK (quantity_ordered > 0),

    CONSTRAINT order_items_unit_price_non_negative
        CHECK (unit_price >= 0),

    CONSTRAINT order_items_unit_cost_labor_non_negative
        CHECK (unit_cost_labor >= 0),

    CONSTRAINT order_items_unit_cost_ingredient_non_negative
        CHECK (unit_cost_ingredient >= 0),

    CONSTRAINT order_items_unit_cost_utilities_non_negative
        CHECK (unit_cost_utilities >= 0),

    CONSTRAINT order_items_unit_cost_packaging_non_negative
        CHECK (unit_cost_packaging >= 0)
);

CREATE OR REPLACE VIEW public.order_item_readiness AS
WITH open_items AS (
    SELECT
        oi.order_item_id,
        oi.order_id,
        oi.product_id,
        oi.quantity_ordered,
        oi.is_ready_override,

        o.due_date,
        o.created_at,

        ps.stock_quantity,

        CASE
            WHEN oi.is_ready_override = TRUE THEN 0
            ELSE 1
        END AS priority_group

    FROM public.order_items oi

    INNER JOIN public.orders o
        ON o.order_id = oi.order_id

    INNER JOIN public.product_stock ps
        ON ps.product_id = oi.product_id

    WHERE o.status IN ('pending', 'delivered')
),
allocated AS (
    SELECT
        oi.*,

        SUM(oi.quantity_ordered) OVER (
            PARTITION BY oi.product_id
            ORDER BY
                oi.priority_group,
                oi.due_date,
                oi.created_at,
                oi.order_id,
                oi.order_item_id
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS running_quantity

    FROM open_items oi
)
SELECT
    order_item_id,
    order_id,
    product_id,
    quantity_ordered,
    is_ready_override,
    stock_quantity,

    (
        running_quantity <= stock_quantity
    ) AS computed_is_ready,

    COALESCE(
        is_ready_override,
        running_quantity <= stock_quantity
    ) AS is_ready,

    running_quantity

FROM allocated;

CREATE OR REPLACE FUNCTION public.create_order_with_items(
    p_customer_name text,
    p_customer_address text DEFAULT NULL,
    p_due_date date DEFAULT NULL,
    p_notes text DEFAULT NULL,
    p_items jsonb DEFAULT '[]'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_order_id bigint;
    v_item jsonb;
BEGIN
    IF NULLIF(trim(p_customer_name), '') IS NULL THEN
        RAISE EXCEPTION 'Customer name is required';
    END IF;

    IF p_due_date IS NULL THEN
        RAISE EXCEPTION 'Due date is required';
    END IF;

    IF p_items IS NULL
       OR jsonb_typeof(p_items) <> 'array'
       OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'At least one order item is required';
    END IF;

    INSERT INTO public.orders (
        customer_name,
        customer_address,
        due_date,
        notes,
        status
    )
    VALUES (
        trim(p_customer_name),
        NULLIF(trim(p_customer_address), ''),
        p_due_date,
        NULLIF(trim(p_notes), ''),
        'pending'
    )
    RETURNING order_id
    INTO v_order_id;

    FOR v_item IN
        SELECT value
        FROM jsonb_array_elements(p_items)
    LOOP

        IF (v_item->>'product_id') IS NULL THEN
            RAISE EXCEPTION 'Every order item requires product_id';
        END IF;

        IF (v_item->>'quantity_ordered') IS NULL
           OR (v_item->>'quantity_ordered')::integer <= 0 THEN
            RAISE EXCEPTION 'Order item quantity must be greater than zero';
        END IF;

        IF (v_item->>'unit_price') IS NULL
           OR (v_item->>'unit_price')::numeric < 0 THEN
            RAISE EXCEPTION 'Order item unit_price must be zero or greater';
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM public.products p
            WHERE p.product_id = (v_item->>'product_id')::bigint
              AND p.deleted_at IS NULL
              AND p.is_active = TRUE
        ) THEN
            RAISE EXCEPTION
                'Product % does not exist or is inactive',
                v_item->>'product_id';
        END IF;

        INSERT INTO public.order_items (
            order_id,
            product_id,
            quantity_ordered,
            unit_price,
            unit_cost_labor,
            unit_cost_ingredient,
            unit_cost_utilities,
            unit_cost_packaging
        )
        VALUES (
            v_order_id,
            (v_item->>'product_id')::bigint,
            (v_item->>'quantity_ordered')::integer,
            (v_item->>'unit_price')::numeric,

            COALESCE(
                (v_item->>'unit_cost_labor')::numeric,
                0
            ),

            COALESCE(
                (v_item->>'unit_cost_ingredient')::numeric,
                0
            ),

            COALESCE(
                (v_item->>'unit_cost_utilities')::numeric,
                0
            ),

            COALESCE(
                (v_item->>'unit_cost_packaging')::numeric,
                0
            )
        );
    END LOOP;

    RETURN v_order_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_orders_overview(
    p_statuses text[] DEFAULT ARRAY['pending']::text[],
    p_page integer DEFAULT 1,
    p_items_per_page integer DEFAULT 20
)
RETURNS TABLE (
    order_id bigint,
    customer_name text,
    customer_address text,
    due_date date,
    status text,
    notes text,
    created_at timestamptz,

    item_count bigint,
    ready_count bigint,
    total_count bigint,

    order_detail jsonb,

    total_pages bigint,
    total_orders bigint
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_total_orders bigint;
BEGIN
    IF p_page < 1 THEN
        RAISE EXCEPTION 'Page must be greater than zero';
    END IF;

    IF p_items_per_page < 1 THEN
        RAISE EXCEPTION 'Items per page must be greater than zero';
    END IF;

    SELECT COUNT(*)
    INTO v_total_orders
    FROM public.orders o
    WHERE o.status = ANY(p_statuses);

    RETURN QUERY
    SELECT
        o.order_id,
        o.customer_name,
        o.customer_address,
        o.due_date,
        o.status,
        o.notes,
        o.created_at,

        COUNT(oi.order_item_id) AS item_count,

        COUNT(*) FILTER (
            WHERE r.is_ready = TRUE
        ) AS ready_count,

        COUNT(oi.order_item_id) AS total_count,

        COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'order_item_id', oi.order_item_id,
                    'product_id', oi.product_id,
                    'product_name', p.product_name,
                    'quantity_ordered', oi.quantity_ordered,
                    'unit_price', oi.unit_price,
                    'unit_cost_labor', oi.unit_cost_labor,
                    'unit_cost_ingredient', oi.unit_cost_ingredient,
                    'unit_cost_utilities', oi.unit_cost_utilities,
                    'unit_cost_packaging', oi.unit_cost_packaging,
                    'is_ready_override', oi.is_ready_override,
                    'computed_is_ready', r.computed_is_ready,
                    'is_ready', r.is_ready
                )
                ORDER BY
                    oi.order_item_id
            ) FILTER (
                WHERE oi.order_item_id IS NOT NULL
            ),
            '[]'::jsonb
        ) AS order_detail,

        CEIL(
            v_total_orders::numeric / p_items_per_page
        )::bigint AS total_pages,

        v_total_orders AS total_orders

    FROM public.orders o

    LEFT JOIN public.order_items oi
        ON oi.order_id = o.order_id

    LEFT JOIN public.products p
        ON p.product_id = oi.product_id

    LEFT JOIN public.order_item_readiness r
        ON r.order_item_id = oi.order_item_id

    WHERE o.status = ANY(p_statuses)

    GROUP BY
        o.order_id,
        o.customer_name,
        o.customer_address,
        o.due_date,
        o.status,
        o.notes,
        o.created_at

    ORDER BY
        o.due_date ASC,
        o.created_at ASC,
        o.order_id ASC

    LIMIT p_items_per_page
    OFFSET (p_page - 1) * p_items_per_page;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_order_detail(
    p_order_id bigint
)
RETURNS TABLE (
    order_item_id bigint,
    product_id bigint,
    product_name text,
    quantity_ordered integer,
    stock_quantity integer,
    is_ready_override boolean,
    computed_is_ready boolean,
    is_ready boolean,
    unit_price numeric
)
LANGUAGE sql
AS $$
    SELECT
        oi.order_item_id,
        oi.product_id,
        p.product_name,
        oi.quantity_ordered,
        r.stock_quantity,
        oi.is_ready_override,
        r.computed_is_ready,
        r.is_ready,
        oi.unit_price

    FROM public.order_items oi

    INNER JOIN public.products p
        ON p.product_id = oi.product_id

    INNER JOIN public.order_item_readiness r
        ON r.order_item_id = oi.order_item_id

    WHERE oi.order_id = p_order_id

    ORDER BY oi.order_item_id;
$$;


CREATE OR REPLACE FUNCTION public.get_product_demand_overview()
RETURNS TABLE (
    product_id bigint,
    product_name text,
    stock_quantity integer,
    total_demand bigint,
    nearest_due_date date,
    shortfall bigint
)
LANGUAGE sql
AS $$
    SELECT
        oi.product_id,
        p.product_name,
        ps.stock_quantity,

        SUM(oi.quantity_ordered)::bigint AS total_demand,

        MIN(o.due_date) AS nearest_due_date,

        GREATEST(
            SUM(oi.quantity_ordered)::bigint
                - ps.stock_quantity,
            0
        )::bigint AS shortfall

    FROM public.order_items oi

    INNER JOIN public.orders o
        ON o.order_id = oi.order_id

    INNER JOIN public.products p
        ON p.product_id = oi.product_id

    INNER JOIN public.product_stock ps
        ON ps.product_id = oi.product_id

    WHERE o.status IN ('pending', 'delivered')

    GROUP BY
        oi.product_id,
        p.product_name,
        ps.stock_quantity

    ORDER BY
        nearest_due_date ASC,
        p.product_name ASC;
$$;


CREATE OR REPLACE FUNCTION public.set_order_item_ready_override(
    p_order_item_id bigint,
    p_value boolean
)
RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
    v_product_id bigint;
    v_order_id bigint;
    v_quantity integer;
    v_status text;

    v_stock integer;
    v_reserved_priority bigint;
BEGIN
    SELECT
        oi.product_id,
        oi.order_id,
        oi.quantity_ordered,
        o.status
    INTO
        v_product_id,
        v_order_id,
        v_quantity,
        v_status

    FROM public.order_items oi

    INNER JOIN public.orders o
        ON o.order_id = oi.order_id

    WHERE oi.order_item_id = p_order_item_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Order item % does not exist',
            p_order_item_id;
    END IF;

    IF v_status NOT IN ('pending', 'delivered') THEN
        RAISE EXCEPTION
            'Cannot change readiness of an order item belonging to a % order',
            v_status;
    END IF;

    -- Clearing the override.
    IF p_value IS NULL THEN

        UPDATE public.order_items
        SET is_ready_override = NULL
        WHERE order_item_id = p_order_item_id;

        RETURN TRUE;
    END IF;

    -- Explicitly marking as not ready.
    IF p_value = FALSE THEN

        UPDATE public.order_items
        SET is_ready_override = FALSE
        WHERE order_item_id = p_order_item_id;

        RETURN TRUE;
    END IF;

    /*
     * TRUE override:
     *
     * Lock the stock row so that another stock-changing operation
     * cannot modify the available stock while we validate this.
     */
    SELECT ps.stock_quantity
    INTO v_stock
    FROM public.product_stock ps
    WHERE ps.product_id = v_product_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Stock record does not exist for product %',
            v_product_id;
    END IF;

    /*
     * Every other TRUE override has priority before normal FIFO.
     * The requested item itself is excluded from this sum.
     */
    SELECT COALESCE(SUM(oi.quantity_ordered), 0)
    INTO v_reserved_priority

    FROM public.order_items oi

    INNER JOIN public.orders o
        ON o.order_id = oi.order_id

    WHERE oi.product_id = v_product_id
      AND oi.order_item_id <> p_order_item_id
      AND oi.is_ready_override = TRUE
      AND o.status IN ('pending', 'delivered');

    IF v_reserved_priority + v_quantity > v_stock THEN
        RAISE EXCEPTION
            'Order item % cannot be marked ready: required quantity % exceeds available stock after existing priority allocations (%)',
            p_order_item_id,
            v_quantity,
            v_stock - v_reserved_priority;
    END IF;

    UPDATE public.order_items
    SET is_ready_override = TRUE
    WHERE order_item_id = p_order_item_id;

    RETURN TRUE;
END;
$$;


CREATE OR REPLACE FUNCTION public.update_order_status(
    p_order_id bigint,
    p_status text
)
RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_status text;
BEGIN
    IF p_status NOT IN ('delivered', 'cancelled') THEN
        RAISE EXCEPTION
            'Invalid target status: %. Only delivered or cancelled are allowed',
            p_status;
    END IF;

    SELECT status
    INTO v_current_status
    FROM public.orders
    WHERE order_id = p_order_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Order % does not exist',
            p_order_id;
    END IF;

    IF v_current_status NOT IN ('pending', 'delivered') THEN
        RAISE EXCEPTION
            'Cannot change status of a % order',
            v_current_status;
    END IF;

    IF v_current_status = 'delivered'
       AND p_status = 'delivered' THEN
        RETURN TRUE;
    END IF;

    UPDATE public.orders
    SET status = p_status
    WHERE order_id = p_order_id;

    RETURN TRUE;
END;
$$;